#!/bin/sh

# Intel macOS Phase 0 settings. Override only the PCIE_* environment variables when
# a local port or temporary directory conflicts with another process.
# Resolve the repository root in a clean non-interactive shell. Interactive zsh
# may run a chpwd hook that writes to stdout; doing the cd directly inside this
# command substitution would then corrupt PCIE_PROJECT_DIR with extra lines.
PCIE_PROJECT_DIR=$(
	/bin/sh -c 'CDPATH= cd -- "$(dirname -- "$1")/../../.." && pwd -P' \
		pcie-config "$0"
)
PCIE_PHASE0_DIR=${PCIE_PHASE0_DIR:-/private/tmp/pcie-phase0}
PCIE_GUEST_IMAGE_URL=https://cloud-images.ubuntu.com/releases/releases/noble/release-20260814/ubuntu-24.04-server-cloudimg-amd64.img
PCIE_GUEST_IMAGE_SHA256=6e40c07ae715f744f84af0bec76415cc1987dd115b4b8de437818561f01a3733
PCIE_GUEST_IMAGE=${PCIE_PHASE0_DIR}/noble-server-cloudimg-amd64.img
PCIE_GUEST_OVERLAY=${PCIE_PHASE0_DIR}/guest-overlay.qcow2
PCIE_SEED_DIR=${PCIE_PHASE0_DIR}/seed
PCIE_SEED_ISO=${PCIE_PHASE0_DIR}/seed.iso
PCIE_SSH_KEY=${PCIE_PHASE0_DIR}/id_ed25519
PCIE_SSH_PORT=${PCIE_SSH_PORT:-2222}
PCIE_GUEST_USER=pcie
PCIE_KERNEL_RELEASE=6.8.0-137-generic
PCIE_KERNEL_HEADERS_VERSION=6.8.0-137.137
PCIE_BUILDER_IMAGE=pcie-phase0-module-builder:6.8.0-137
PCIE_QEMU_PID=${PCIE_PHASE0_DIR}/qemu.pid
PCIE_QEMU_MONITOR=${PCIE_PHASE0_DIR}/monitor.sock
PCIE_SERIAL_LOG=${PCIE_PHASE0_DIR}/serial.log
PCIE_MODULE_OUTPUT=${PCIE_PHASE0_DIR}/module-out
PCIE_DEBUG_KERNEL_VERSION=6.12.101
PCIE_DEBUG_KERNEL_SHA256=0d21cd11933f49f7151b7c9dbb8cc3fddc8c8abe506434b850feecf41fc28a76
PCIE_DEBUG_KERNEL_TARBALL=${PCIE_PHASE0_DIR}/linux-${PCIE_DEBUG_KERNEL_VERSION}.tar.xz
PCIE_DEBUG_KERNEL_VOLUME=pcie-kernel-${PCIE_DEBUG_KERNEL_VERSION}
PCIE_DEBUG_KERNEL_OUTPUT=${PCIE_PHASE0_DIR}/debug-kernel-output
PCIE_DEBUG_BZIMAGE=${PCIE_DEBUG_KERNEL_OUTPUT}/bzImage-${PCIE_DEBUG_KERNEL_VERSION}-pcie-lab
PCIE_DEBUG_VMLINUX=${PCIE_DEBUG_KERNEL_OUTPUT}/vmlinux-${PCIE_DEBUG_KERNEL_VERSION}-pcie-lab
PCIE_KERNEL_BUILDER_IMAGE=pcie-phase0-kernel-builder:ubuntu-24.04
PCIE_GDB_PORT=${PCIE_GDB_PORT:-1234}
PCIE_DEBUG_SERIAL_LOG=${PCIE_PHASE0_DIR}/debug-serial.log

export PCIE_PROJECT_DIR PCIE_PHASE0_DIR PCIE_GUEST_IMAGE_URL
export PCIE_GUEST_IMAGE_SHA256 PCIE_GUEST_IMAGE PCIE_GUEST_OVERLAY
export PCIE_SEED_DIR PCIE_SEED_ISO PCIE_SSH_KEY PCIE_SSH_PORT
export PCIE_GUEST_USER PCIE_KERNEL_RELEASE PCIE_KERNEL_HEADERS_VERSION
export PCIE_BUILDER_IMAGE PCIE_QEMU_PID PCIE_QEMU_MONITOR
export PCIE_SERIAL_LOG PCIE_MODULE_OUTPUT
export PCIE_DEBUG_KERNEL_VERSION PCIE_DEBUG_KERNEL_SHA256
export PCIE_DEBUG_KERNEL_TARBALL PCIE_DEBUG_KERNEL_VOLUME
export PCIE_DEBUG_KERNEL_OUTPUT PCIE_DEBUG_BZIMAGE PCIE_DEBUG_VMLINUX
export PCIE_KERNEL_BUILDER_IMAGE PCIE_GDB_PORT PCIE_DEBUG_SERIAL_LOG
